### ISSUE TITLE
pyro的包名不对

### ISSUE THREAD

**Issue by kadaliao** [laixintao/python-parallel-programming-cookbook-cn#81]
6.1 节中，`pip install pyro-ppl`才能正确安装pyro

ref: https://github.com/pyro-ppl/pyro/issues/578

**Comment by laixintao** [comment]
https://pypi.org/project/pyro-ppl/ 应该是一个概率编程的库

**Comment by kadaliao** [comment]
> https://pypi.org/project/pyro-ppl/ 应该是一个概率编程的库

是的。安装不了应该是别的问题。

**Comment by laixintao** [comment]
官方网站 https://pypi.org/project/Pyro/ 说 pyro 这个包已经不在维护了。可以试试 `pip install pyro4` 不过可能 API 会有一些不兼容。如果发现欢迎pr
