### ISSUE TITLE
非常赞！请问前端是拿什么实现的呢？

### ISSUE THREAD

**Issue by dongrixinyu** [laixintao/python-parallel-programming-cookbook-cn#91]
非常赞！请问前端是拿什么实现的呢？
我在看你的并行处理文章，我也有在写NLP相关的文章，想以个人网站发布出来，但是发现对公式的支持不太漂亮，所以想问一下。

BTW，shopee 现在有NLP 的岗位可以内推吗？

**Comment by laixintao** [comment]
是 sphinx build 的，可以看这里：https://github.com/laixintao/python-parallel-programming-cookbook-cn/blob/master/.circleci/config.yml#L14

内推可以在 https://careers.shopee.sg/ 查看有没有合适的职位，然后发送简历给我。
